server:
  port: 10001
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:product_db}:3306/product?serverTimezone=UTC
    username: coupang
    password: coupang
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

  instance:
    lease-renewal-interval-in-seconds: 3
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


#  docker run --name product_db --network edu -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=coupang -e MYSQL_PASSWORD=coupang -e MYSQL_DATABASE=product -p 13306:3306 -d mysql:8.0

# docker build ./ -t config-server:latest
# docker run --name config-server -p 8888:8888 config-server:latest